"""AEON Init — Project onboarding wizard.

Interactive setup that detects project languages, creates .aeonrc.yml
with sensible defaults, runs an initial scan, and suggests a profile.

Usage:
    aeon init              # Interactive setup wizard
    aeon init --ci         # Generate GitHub Actions workflow file
    aeon init --profile security  # Set up with a specific profile
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from aeon.profiles import PROFILES, get_profile, profile_names


# ── Language detection ──────────────────────────────────────────────────

_EXT_MAP = {
    ".py": "Python", ".java": "Java", ".js": "JavaScript", ".jsx": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TypeScript", ".go": "Go", ".rs": "Rust",
    ".c": "C", ".h": "C", ".cpp": "C++", ".hpp": "C++", ".cc": "C++",
    ".rb": "Ruby", ".swift": "Swift", ".kt": "Kotlin", ".kts": "Kotlin",
    ".php": "PHP", ".scala": "Scala", ".dart": "Dart", ".aeon": "AEON",
    ".lua": "Lua", ".r": "R", ".R": "R", ".ex": "Elixir", ".exs": "Elixir",
    ".hs": "Haskell", ".ml": "OCaml", ".zig": "Zig", ".jl": "Julia",
}


def detect_languages(directory: str) -> Dict[str, int]:
    """Detect programming languages used in a directory.

    Returns a dict of {language_name: file_count}.
    """
    counts: Dict[str, int] = {}
    skip_dirs = {".git", "node_modules", ".venv", "venv", "__pycache__",
                 "vendor", "build", "dist", ".tox", ".mypy_cache"}

    for root, dirs, files in os.walk(directory):
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        for fname in files:
            ext = os.path.splitext(fname)[1].lower()
            lang = _EXT_MAP.get(ext)
            if lang:
                counts[lang] = counts.get(lang, 0) + 1

    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def suggest_profile(languages: Dict[str, int], directory: str) -> str:
    """Suggest the best profile based on project type."""
    total_files = sum(languages.values())

    # Check for web app indicators
    has_web = any(os.path.isfile(os.path.join(directory, f))
                  for f in ["package.json", "requirements.txt", "Gemfile",
                            "Cargo.toml", "go.mod"])

    web_langs = {"JavaScript", "TypeScript", "PHP", "Ruby"}
    web_file_count = sum(languages.get(l, 0) for l in web_langs)

    # Check for framework files
    has_django = os.path.isfile(os.path.join(directory, "manage.py"))
    has_flask = any("flask" in str(f).lower() for f in Path(directory).rglob("requirements*.txt"))
    has_express = os.path.isfile(os.path.join(directory, "package.json"))

    if has_django or has_flask or has_express or (web_file_count > total_files * 0.5):
        return "security"

    # Systems languages → safety
    systems_langs = {"C", "C++", "Rust", "Go", "Zig"}
    systems_count = sum(languages.get(l, 0) for l in systems_langs)
    if systems_count > total_files * 0.5:
        return "safety"

    # Small project → quick
    if total_files < 10:
        return "quick"

    return "daily"


# ── Config generation ───────────────────────────────────────────────────

def generate_aeonrc(
    directory: str,
    profile_name: str = "daily",
    languages: Optional[Dict[str, int]] = None,
) -> str:
    """Generate .aeonrc.yml content."""
    if languages is None:
        languages = detect_languages(directory)

    profile = get_profile(profile_name)
    profile_desc = profile.description if profile else "Daily driver"

    # Build include patterns from detected languages
    ext_patterns = set()
    lang_to_ext = {
        "Python": "*.py", "Java": "*.java", "JavaScript": "*.js",
        "TypeScript": "*.ts", "Go": "*.go", "Rust": "*.rs",
        "C": "*.c", "C++": "*.cpp", "Ruby": "*.rb", "Swift": "*.swift",
        "Kotlin": "*.kt", "PHP": "*.php", "Scala": "*.scala",
        "Dart": "*.dart", "AEON": "*.aeon",
    }
    for lang in languages:
        if lang in lang_to_ext:
            ext_patterns.add(lang_to_ext[lang])

    lines = [
        f"# AEON Configuration",
        f"# Profile: {profile_name} — {profile_desc}",
        f"# Generated by: aeon init",
        f"",
        f"# Analysis profile (quick | daily | security | performance | safety)",
        f"profile: {profile_name}",
        f"",
        f"# Enable deep verification (all engines)",
        f"deep_verify: {'true' if profile_name == 'safety' else 'false'}",
        f"",
        f"# Parallel scanning",
        f"parallel: true",
        f"",
        f"# Output format (text | json | sarif | markdown)",
        f"format: text",
        f"",
        f"# File patterns to include",
        f"include:",
    ]
    for pat in sorted(ext_patterns):
        lines.append(f'  - "src/**/{pat}"')
        lines.append(f'  - "lib/**/{pat}"')
    if not ext_patterns:
        lines.append(f'  - "**/*.py"')

    lines.extend([
        f"",
        f"# Directories to exclude",
        f"exclude:",
        f'  - "tests/**"',
        f'  - "test/**"',
        f'  - "vendor/**"',
        f'  - "node_modules/**"',
        f'  - ".venv/**"',
        f'  - "build/**"',
        f'  - "dist/**"',
    ])

    return "\n".join(lines) + "\n"


def generate_github_workflow() -> str:
    """Generate a GitHub Actions workflow for AEON verification."""
    return """\
name: AEON Verify
on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AEON
        run: pip install aeon-lang

      - name: Run AEON Verification
        run: aeon scan src/ --deep-verify --format sarif > aeon-results.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: aeon-results.sarif

      - name: AEON Code Review
        if: github.event_name == 'pull_request'
        run: |
          aeon review --diff origin/${{ github.base_ref }}..HEAD --format markdown > review.md
          echo "## AEON Code Review" >> $GITHUB_STEP_SUMMARY
          cat review.md >> $GITHUB_STEP_SUMMARY
"""


# ── Init command ────────────────────────────────────────────────────────

def run_init(
    directory: str = ".",
    profile: Optional[str] = None,
    generate_ci: bool = False,
    quiet: bool = False,
) -> Dict[str, Any]:
    """Run the AEON init wizard.

    Returns a dict summarizing what was created.
    """
    directory = os.path.abspath(directory)
    result: Dict[str, Any] = {"created": [], "skipped": [], "summary": ""}

    if not quiet:
        print(f"\n🔧 AEON Init — Setting up verification for your project")
        print(f"   Directory: {directory}")
        print(f"   {'─' * 45}")

    # 1. Detect languages
    languages = detect_languages(directory)
    if not quiet:
        if languages:
            print(f"\n   📂 Detected languages:")
            for lang, count in list(languages.items())[:8]:
                print(f"      • {lang}: {count} file{'s' if count != 1 else ''}")
        else:
            print(f"\n   ⚠️  No supported source files detected.")

    # 2. Suggest / use profile
    if profile is None:
        profile = suggest_profile(languages, directory)
    if not quiet:
        prof = get_profile(profile)
        desc = prof.description if prof else ""
        print(f"\n   🎯 Profile: {profile} — {desc}")

    # 3. Generate .aeonrc.yml
    config_path = os.path.join(directory, ".aeonrc.yml")
    if os.path.exists(config_path):
        if not quiet:
            print(f"\n   ⏭  .aeonrc.yml already exists — skipping")
        result["skipped"].append(config_path)
    else:
        config_content = generate_aeonrc(directory, profile, languages)
        with open(config_path, "w") as f:
            f.write(config_content)
        if not quiet:
            print(f"\n   ✅ Created .aeonrc.yml")
        result["created"].append(config_path)

    # 4. Generate CI workflow if requested
    if generate_ci:
        ci_dir = os.path.join(directory, ".github", "workflows")
        ci_path = os.path.join(ci_dir, "aeon-verify.yml")
        if os.path.exists(ci_path):
            if not quiet:
                print(f"   ⏭  .github/workflows/aeon-verify.yml already exists — skipping")
            result["skipped"].append(ci_path)
        else:
            os.makedirs(ci_dir, exist_ok=True)
            with open(ci_path, "w") as f:
                f.write(generate_github_workflow())
            if not quiet:
                print(f"   ✅ Created .github/workflows/aeon-verify.yml")
            result["created"].append(ci_path)

    # 5. Run initial scan
    if not quiet:
        total_files = sum(languages.values())
        print(f"\n   📊 Project summary:")
        print(f"      {total_files} source files across {len(languages)} language(s)")
        print(f"      Profile: {profile}")
        print(f"\n   💡 Next steps:")
        print(f"      • Run: aeon check <file>           — verify a single file")
        print(f"      • Run: aeon scan src/              — scan a directory")
        print(f"      • Run: aeon fix <file>             — auto-fix issues")
        print(f"      • Run: aeon review <file>          — get a code review")
        if not generate_ci:
            print(f"      • Run: aeon init --ci             — add GitHub Actions workflow")
        print()

    result["summary"] = (
        f"Initialized AEON with '{profile}' profile for "
        f"{sum(languages.values())} files in {len(languages)} language(s)."
    )

    return result
